// ============================================================================
// File: resource.h
// Description: Resource identifiers for NetPulse
// Author: NetPulse Project
// Note: This file is typically auto-generated by Visual Studio Resource Editor
// ============================================================================

#ifndef NETWORK_MONITOR_RESOURCE_H
#define NETWORK_MONITOR_RESOURCE_H

// ============================================================================
// ICON RESOURCES
// ============================================================================

#define IDI_APP_ICON                    101
#define IDI_TRAY_IDLE                   102
#define IDI_TRAY_ACTIVE                 103
#define IDI_TRAY_HIGH                   104

// Optional dark-variant icons (fallback to normal icons if resources not present)
#define IDI_APP_ICON_DARK               105
#define IDI_TRAY_IDLE_DARK              106
#define IDI_TRAY_ACTIVE_DARK            107
#define IDI_TRAY_HIGH_DARK              108

// ============================================================================
// MENU RESOURCES
// ============================================================================

#define IDR_TRAY_MENU                   201
#define IDR_UPDATE_MENU                 202

// ============================================================================
// MENU ITEM IDS
// ============================================================================

#define IDM_SETTINGS                    1001
#define IDM_ABOUT                       1002
#define IDM_EXIT                        1003
#define IDM_AUTOSTART                   1004
#define IDM_UPDATE_FAST                 1005
#define IDM_UPDATE_NORMAL               1006
#define IDM_UPDATE_SLOW                 1007
#define IDM_SHOW_TASKBAR_OVERLAY        1008 
#define IDM_DASHBOARD                   1009
#define IDM_SHOW_FLOATING_WINDOW        1010
#define IDM_PERAPP                      1011
#define IDM_CHECK_FOR_UPDATES           1012

// ============================================================================
// DIALOG RESOURCES
// ============================================================================

#define IDD_ABOUT_DIALOG                301
#define IDD_SETTINGS_DIALOG             302
#define IDD_DASHBOARD_DIALOG            303
#define IDD_HISTORY_MANAGE_DIALOG       304
#define IDD_MESSAGE_DIALOG              305
#define IDD_PERAPP_DIALOG               306
#define IDD_SPEED_TEST_DIALOG           307
#define IDD_CONNECTION_LOG_DIALOG       308

// Per-App Dialog Controls
#define IDC_PERAPP_LIST                 3060
#define IDC_PERAPP_REFRESH              3061

// Connection Log Dialog Controls
#define IDC_CONNLOG_LIST                3080
#define IDC_CONNLOG_REFRESH             3081

// Dashboard Chart Navigation Controls
#define IDC_CHART_VIEW_DAILY            3090
#define IDC_CHART_VIEW_MONTHLY          3091
#define IDC_CHART_NAV_PREV              3092
#define IDC_CHART_NAV_NEXT              3093
#define IDC_CHART_TITLE                 3094

// ============================================================================
// STRING RESOURCES
// ============================================================================

#define IDS_APP_TITLE                   401
#define IDS_ERROR_INIT                  402
#define IDS_ERROR_NETWORK               403
#define IDS_ERROR_ALREADY_RUNNING       404
#define IDS_ERR_REGISTER_WINDOW_CLASS   405
#define IDS_ERR_CREATE_WINDOW           406
#define IDS_ERR_INIT_TRAY_ICON          407
#define IDS_ERR_INIT_TASKBAR_OVERLAY    408
#define IDS_ERR_START_NETWORK_MONITOR   409
#define IDS_ERR_LOAD_APP_ICON           410
#define IDS_ERR_CREATE_TRAY_ICON        411
#define IDS_ERR_REGISTER_OVERLAY        4111
#define IDS_ERR_CREATE_OVERLAY          4112
#define IDS_MENU_UPDATE_INTERVAL        412
#define IDS_MENU_UPDATE_FAST            413
#define IDS_MENU_UPDATE_NORMAL          414
#define IDS_MENU_UPDATE_SLOW            415
#define IDS_MENU_AUTOSTART              416
#define IDS_MENU_TASKBAR_OVERLAY        417
#define IDS_MENU_SETTINGS               418
#define IDS_MENU_DASHBOARD              419
#define IDS_MENU_ABOUT                  420
#define IDS_MENU_EXIT                   421
#define IDS_DASHBOARD_COL_TIME          422
#define IDS_DASHBOARD_COL_INTERFACE     423
#define IDS_DASHBOARD_COL_DOWN          424
#define IDS_DASHBOARD_COL_UP            425
#define IDS_INTERVAL_FAST               426
#define IDS_INTERVAL_NORMAL             427
#define IDS_INTERVAL_SLOW               428
#define IDS_UNIT_BYTES_PER_SECOND       429
#define IDS_UNIT_KILOBYTES_PER_SECOND   430
#define IDS_UNIT_MEGABYTES_PER_SECOND   431
#define IDS_UNIT_MEGABITS_PER_SECOND    432
#define IDS_ALL_INTERFACES              433
#define IDS_AGGREGATED_STATS            434
#define IDS_OVERLAY_DOWN_PREFIX         435
#define IDS_OVERLAY_UP_PREFIX           436
#define IDS_ABOUT_TITLE                 437
#define IDS_ABOUT_VERSION_LABEL         438
#define IDS_ABOUT_BODY                  439
#define IDS_HISTORY_MANAGE_TITLE        440
#define IDS_HISTORY_CONFIRM_DELETE_ALL  441
#define IDS_HISTORY_CONFIRM_TRIM_30     442
#define IDS_HISTORY_CONFIRM_TRIM_90     443
#define IDS_HISTORY_ERROR_OPERATION     444
#define IDS_HISTORY_AUTO_TRIM_NONE      445
#define IDS_HISTORY_AUTO_TRIM_7D        446
#define IDS_HISTORY_AUTO_TRIM_30D       447
#define IDS_HISTORY_AUTO_TRIM_90D       448
#define IDS_HISTORY_AUTO_TRIM_365D      449
#define IDS_LANGUAGE_SYSTEM             450
#define IDS_LANGUAGE_ENGLISH            451
#define IDS_LANGUAGE_VIETNAMESE         452
#define IDS_LANGUAGE_JAPANESE           486
#define IDS_LANGUAGE_KOREAN             487
#define IDS_LANGUAGE_CHINESE_SIMPLIFIED 488
#define IDS_SETTINGS_TITLE              453
#define IDS_SETTINGS_GROUP_GENERAL      454
#define IDS_SETTINGS_GROUP_UPDATE       455
#define IDS_SETTINGS_GROUP_NETWORK      456
#define IDS_SETTINGS_LABEL_LANGUAGE     457
#define IDS_SETTINGS_LABEL_AUTOSTART    458
#define IDS_SETTINGS_LABEL_LOGGING      459
#define IDS_SETTINGS_LABEL_INTERVAL     460
#define IDS_SETTINGS_LABEL_SPEED_UNIT   461
#define IDS_SETTINGS_LABEL_MONITOR      462
#define IDS_SETTINGS_LABEL_AUTOTRIM     463
#define IDS_DASHBOARD_TITLE             464
#define IDS_DASHBOARD_LABEL_TODAY       465
#define IDS_DASHBOARD_LABEL_THIS_MONTH  466
#define IDS_DASHBOARD_LABEL_DOWNLOAD    467
#define IDS_DASHBOARD_LABEL_UPLOAD      468
#define IDS_HISTORY_DIALOG_TITLE        469
#define IDS_HISTORY_LABEL_OPERATIONS    470
#define IDS_HISTORY_BUTTON_DELETE_ALL   471
#define IDS_HISTORY_BUTTON_KEEP_30      472
#define IDS_HISTORY_BUTTON_KEEP_90      473
#define IDS_SETTINGS_LABEL_DEBUGLOGGING 474
#define IDS_SETTINGS_BUTTON_OPEN_LOG    475
#define IDS_DASHBOARD_BUTTON_EXPORT_CSV 476
#define IDS_SETTINGS_LABEL_DARK_THEME   477
#define IDS_SETTINGS_THEME_SYSTEM       478
#define IDS_SETTINGS_THEME_LIGHT        479
#define IDS_SETTINGS_THEME_DARK         480
#define IDS_NOTIFICATION_DISCONNECTED_TITLE 481
#define IDS_NOTIFICATION_DISCONNECTED_MSG   482
#define IDS_NOTIFICATION_CONNECTED_TITLE    483
#define IDS_NOTIFICATION_CONNECTED_MSG      484
#define IDS_SETTINGS_LABEL_CONNECTION_NOTIFY 485

// Tab names
#define IDS_SETTINGS_TAB_GENERAL        489
#define IDS_SETTINGS_TAB_DISPLAY        490
#define IDS_SETTINGS_TAB_ADVANCED       491

// Button labels
#define IDS_BUTTON_OK                   492
#define IDS_BUTTON_CANCEL               493
#define IDS_BUTTON_APPLY                494
#define IDS_DASHBOARD_BUTTON_REFRESH    495
#define IDS_DASHBOARD_BUTTON_CLOSE      496
#define IDS_DASHBOARD_BUTTON_MANAGE     497

// Data Usage Alerts strings
#define IDS_DATA_USAGE_TITLE            498
#define IDS_DATA_USAGE_ENABLE           499
#define IDS_DATA_USAGE_QUOTA            500
#define IDS_DATA_USAGE_ALERT_MSG        501
#define IDS_DATA_USAGE_UNIT_GB          502

// Additional Settings labels (missing i18n)
#define IDS_SETTINGS_LABEL_OVERLAY_FONT_SIZE  503
#define IDS_SETTINGS_LABEL_OVERLAY_COLORS     504
#define IDS_SETTINGS_LABEL_PING_TARGET        505
#define IDS_SETTINGS_LABEL_PING_INTERVAL      506
#define IDS_SETTINGS_LABEL_HOTKEY             507
#define IDS_DATA_USAGE_QUOTA_GB               508
#define IDS_SETTINGS_LABEL_DATA_USAGE_ENABLE  509

// ============================================================================
// CONTROL IDS (for dialogs)
// ============================================================================

#define IDC_STATIC                      -1
#define IDC_VERSION_TEXT                501
#define IDC_COPYRIGHT_TEXT              1054
#define IDC_GITHUB_LINK                 1055
#define IDC_UPDATE_INTERVAL_COMBO       503
#define IDC_DISPLAY_UNIT_COMBO          504
#define IDC_AUTOSTART_CHECK             505
#define IDC_INTERFACE_COMBO             506
#define IDC_TODAY_DOWN                  507
#define IDC_TODAY_UP                    508
#define IDC_MONTH_DOWN                  509
#define IDC_MONTH_UP                    510
#define IDC_RECENT_LIST                 511
#define IDC_ENABLE_LOGGING_CHECK        512
#define IDC_DASHBOARD_REFRESH           513
#define IDC_HISTORY_DELETE_ALL          514
#define IDC_HISTORY_KEEP_30             515
#define IDC_HISTORY_KEEP_90             516
#define IDC_HISTORY_MANAGE              517
#define IDC_HISTORY_AUTO_TRIM_COMBO     518
#define IDC_DASHBOARD_CHART             519
#define IDC_LANGUAGE_COMBO              520
#define IDC_SETTINGS_GROUP_GENERAL      521
#define IDC_SETTINGS_GROUP_UPDATE       522
#define IDC_SETTINGS_GROUP_NETWORK      523
#define IDC_SETTINGS_LABEL_LANGUAGE     524
#define IDC_SETTINGS_LABEL_INTERVAL     525
#define IDC_SETTINGS_LABEL_SPEED_UNIT   526
#define IDC_SETTINGS_LABEL_MONITOR      527
#define IDC_SETTINGS_LABEL_AUTOTRIM     528
#define IDC_DASHBOARD_LABEL_TODAY       529
#define IDC_DASHBOARD_LABEL_DOWNLOAD_T  530
#define IDC_DASHBOARD_LABEL_UPLOAD_T    531
#define IDC_DASHBOARD_LABEL_MONTH       532
#define IDC_DASHBOARD_LABEL_DOWNLOAD_M  533
#define IDC_DASHBOARD_LABEL_UPLOAD_M    534
#define IDC_HISTORY_LABEL_OPERATIONS    535
#define IDC_DEBUG_LOGGING_CHECK         536
#define IDC_SETTINGS_BUTTON_OPEN_LOG    537
#define IDC_DASHBOARD_BUTTON_EXPORT     538
#define IDC_DASHBOARD_EXPORT_CHART      539
#define IDC_DARK_THEME_CHECK            570
#define IDC_MESSAGE_ICON                540
#define IDC_MESSAGE_TEXT                541
#define IDC_SETTINGS_LABEL_THEME        542
#define IDC_THEME_MODE_COMBO            543
#define IDC_CONNECTION_NOTIFY_CHECK     544
#define IDC_SETTINGS_GROUP_ADVANCED     545
#define IDC_PING_TARGET_EDIT            546
#define IDC_PING_INTERVAL_COMBO         547
#define IDC_HOTKEY_COMBO                548
#define IDC_OVERLAY_FONT_SIZE_COMBO     549
#define IDC_OVERLAY_COLOR_COMBO         550
#define IDC_SETTINGS_TAB                551
#define IDC_DISPLAY_UNIT_LABEL          552
#define IDC_FONT_SIZE_LABEL             553
#define IDC_OVERLAY_COLOR_LABEL         554
#define IDC_HISTORY_TRIM_LABEL          555
#define IDC_PING_TARGET_LABEL           556
#define IDC_PING_INTERVAL_LABEL         557
#define IDC_HOTKEY_LABEL                558
#define IDC_SETTINGS_BUTTON_APPLY       559

// Data Usage Alert controls
#define IDC_DATA_USAGE_ENABLE_CHECK     560
#define IDC_DATA_USAGE_QUOTA_EDIT       561
#define IDC_DATA_USAGE_QUOTA_LABEL      562
#define IDC_DATA_USAGE_THRESHOLD1_EDIT  563
#define IDC_DATA_USAGE_THRESHOLD2_EDIT  564

// PerApp Dialog strings
#define IDS_PERAPP_DIALOG_TITLE         565
#define IDS_PERAPP_COL_APPLICATION      566
#define IDS_PERAPP_COL_PID              567
#define IDS_PERAPP_COL_TCP              568
#define IDS_PERAPP_COL_UDP              569
#define IDS_PERAPP_COL_SENT             570
#define IDS_PERAPP_COL_RECEIVED         571
#define IDS_PERAPP_BUTTON_REFRESH       572
#define IDS_PERAPP_BUTTON_CLOSE         573
#define IDS_MENU_FLOATING_WINDOW        574
#define IDS_MENU_PERAPP                 575
#define IDC_AUTOSTART_ADMIN_CHECK       576
#define IDS_SETTINGS_LABEL_AUTOSTART_ADMIN 577
#define IDC_SETTINGS_GROUP_FLOATING     578
#define IDC_FLOATING_SHOW_NETWORK_CHECK 579
#define IDC_FLOATING_SHOW_CPU_CHECK     580
#define IDC_FLOATING_SHOW_RAM_CHECK     1222
#define IDC_FLOATING_SHOW_PING_CHECK    1223
#define IDC_FLOATING_SHOW_DATA_TODAY_CHECK 1224
#define IDC_FLOATING_SHOW_SPARKLINE_CHECK 1225
#define IDC_BTN_EXPORT_CSV              1226

// Note: standard strings are defined earlier
#define IDS_SETTINGS_GROUP_FLOATING     2100
#define IDS_FLOATING_SHOW_NETWORK       2101
#define IDS_FLOATING_SHOW_CPU           2102
#define IDS_FLOATING_SHOW_RAM           2103
#define IDS_FLOATING_SHOW_PING          2104
#define IDS_FLOATING_SHOW_DATA_TODAY    2105
#define IDS_FLOATING_SHOW_SPARKLINE     2106
#define IDS_BTN_EXPORT_CSV              2107

// Tray Animation settings
#define IDC_TRAY_ANIMATION_CHECK        2110
#define IDC_TRAY_ANIMATION_THRESHOLD    2111
#define IDS_TRAY_ANIMATION_ENABLE       2112
#define IDS_TRAY_ANIMATION_THRESHOLD    2113
#define IDC_SETTINGS_GROUP_TRAY         2120
#define IDC_TRAY_ANIMATION_THRESHOLD_LABEL 2121
#define IDS_SETTINGS_GROUP_TRAY         2130
#define IDS_TRAY_ANIMATION_THRESHOLD_LABEL 2131

// Sparkline Time Range settings
#define IDC_SPARKLINE_TIME_RANGE_LABEL  2140
#define IDC_SPARKLINE_TIME_RANGE_COMBO  2141
#define IDS_SPARKLINE_TIME_RANGE_LABEL  2150
#define IDS_SPARKLINE_30S               2151
#define IDS_SPARKLINE_1M                2152
#define IDS_SPARKLINE_5M                2153

// Export Chart button
#define IDC_EXPORT_CHART_BUTTON         2160
#define IDS_EXPORT_CHART_BUTTON         2161

// Phase 3: VPN/Proxy Detection settings
#define IDC_FLOATING_SHOW_VPN_CHECK     2170
#define IDC_FLOATING_SHOW_IP_CHECK      2171
#define IDS_FLOATING_SHOW_VPN_STATUS    2180
#define IDS_FLOATING_SHOW_PUBLIC_IP     2181

// Floating Window Status & Chart
#define IDS_FLOATING_CHART_TITLE        2190
#define IDS_FLOATING_CHART_DOWNLOAD     2191
#define IDS_FLOATING_CHART_UPLOAD       2192
#define IDS_FLOATING_VPN_STATE_ON       2193
#define IDS_FLOATING_PROXY_STATE_ON     2194
#define IDS_FLOATING_VPN_STATE_OFF      2195
#define IDS_FLOATING_IP_LABEL           2196

// Phase 3: Speed Test
#define IDC_SPEED_TEST_PROGRESS         2201
#define IDC_SPEED_DOWNLOAD_LABEL        2202
#define IDC_SPEED_DOWNLOAD_VALUE        2203
#define IDC_SPEED_UPLOAD_LABEL          2204
#define IDC_SPEED_UPLOAD_VALUE          2205
#define IDC_SPEED_PING_LABEL            2206
#define IDC_SPEED_PING_VALUE            2207
#define IDC_SPEED_STATUS_LABEL          2209
#define IDC_SPEED_HISTORY_LIST          2210
#define IDC_SPEED_START_BUTTON          2211
#define IDC_SPEED_RESULT_GROUP          2212
#define IDC_SPEED_HISTORY_LABEL         2213

#define IDS_SPEED_TEST_BUTTON           2220
#define IDS_SPEED_TESTING               2221
#define IDS_SPEED_DOWNLOAD              2222
#define IDS_SPEED_UPLOAD                2223
#define IDS_SPEED_PING                  2224
#define IDS_SPEED_HISTORY               2225
#define IDS_SPEED_RESULTS               2232
#define IDS_SPEED_TEST_FAILED           2226
#define IDS_SPEED_TEST_COMPLETE         2227
#define IDS_SPEED_CANCEL                2228
#define IDS_SPEED_TEST_DIALOG_TITLE     2229
#define IDS_SPEED_TEST_DOWNLOAD         2230
#define IDS_SPEED_TEST_UPLOAD           2231
// Verified IDs present

// Menu item for Speed Test
#define IDM_SPEED_TEST                  2250
#define IDS_MENU_SPEED_TEST             2251

// Menu item for Connection Log (Phase 4)
#define IDM_CONNECTION_LOG              2260
#define IDS_MENU_CONNECTION_LOG         2261

// Menu item for Check for Updates
#define IDS_MENU_CHECK_FOR_UPDATES      2280

// Connection Log Dialog column headers (i18n)
#define IDS_CONNLOG_COL_PROCESS         2270
#define IDS_CONNLOG_COL_PID             2271
#define IDS_CONNLOG_COL_PROTOCOL        2272
#define IDS_CONNLOG_COL_LOCAL_ADDR      2273
#define IDS_CONNLOG_COL_LOCAL_PORT      2274
#define IDS_CONNLOG_COL_REMOTE_ADDR     2275
#define IDS_CONNLOG_COL_REMOTE_PORT     2276
#define IDS_CONNLOG_COL_STATE           2277

// Portable Mode
#define IDC_PORTABLE_MODE_CHECK         2279
#define IDC_PORTABLE_MODE_BUTTON        2280
#define IDS_PORTABLE_MODE_CHECK         2285
#define IDS_PORTABLE_MODE_BUTTON        2281
#define IDS_PORTABLE_MODE_SUCCESS       2282
#define IDS_PORTABLE_MODE_ALREADY       2283
#define IDS_PORTABLE_MODE_FAILED        2284

// ============================================================================
// STANDARD DIALOG IDS
// ============================================================================

#ifndef IDOK
#define IDOK                            1
#endif

#ifndef IDCANCEL
#define IDCANCEL                        2
#endif

// Custom dialog result for Apply with reopen
#define IDAPPLY_REOPEN                  100

// ============================================================================
// Next default values for new objects
// ============================================================================

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#endif // NETWORK_MONITOR_RESOURCE_H
